# Generated by Django 5.0.7 on 2024-08-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0002_rename_name_translatablestring_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatablestring",
            name="string",
            field=models.CharField(max_length=50000, unique=True),
        ),
    ]
