# Generated by Django 5.0.7 on 2024-08-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0003_alter_translatablestring_string"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatablestring",
            name="string_fr",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="string_nl",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
