# Generated by Django 5.0.7 on 2024-08-04 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0005_sourceproject_translatablestring_source_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatablestring",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="translatablestring",
            name="source_project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="translation_api.sourceproject"),
        ),
    ]
