# Generated by Django 5.0.7 on 2024-08-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0006_translatablestring_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatablestring",
            name="string",
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterUniqueTogether(
            name="translatablestring",
            unique_together={("source_project", "string")},
        ),
    ]
