# Generated by Django 5.0.7 on 2024-08-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0007_alter_translatablestring_string_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatablestring",
            name="string_de",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="string_es",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="string_it",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
