# Generated by Django 5.0.7 on 2024-08-12 21:42

import django.db.models.deletion
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0008_translatablestring_string_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translatablestring",
            name="string_de",
        ),
        migrations.RemoveField(
            model_name="translatablestring",
            name="string_es",
        ),
        migrations.RemoveField(
            model_name="translatablestring",
            name="string_it",
        ),
        migrations.CreateModel(
            name="TranslatedString",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(max_length=10)),
                ("translated_string", models.CharField(max_length=50000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "string",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="translation_api.translatablestring"
                    ),
                ),
            ],
            options={
                "unique_together": {("string", "language")},
            },
        ),
    ]
