# Generated by Django 5.0.7 on 2024-08-12 22:07

from django.db import migrations
# move the string_fr, string_nl to a new model TranslatedString
def migrate_data(apps, schema_editor):
    TranslatableString = apps.get_model("translation_api", "TranslatableString")
    TranslatedString = apps.get_model("translation_api", "TranslatedString")

    for translatable_string in TranslatableString.objects.all():
        if translatable_string.string_fr:
            TranslatedString.objects.create(
                string=translatable_string,
                language="fr",
                translated_string=translatable_string.string_fr,
            )

        if translatable_string.string_nl:
            TranslatedString.objects.create(
                string=translatable_string,
                language="nl",
                translated_string=translatable_string.string_nl,
            )

class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0010_translatedstring_validated_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
