# Generated by Django 5.0.7 on 2024-08-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0012_translatedstring_translated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="translatablestring",
            name="string_fr",
        ),
        migrations.RemoveField(
            model_name="translatablestring",
            name="string_nl",
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="context",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name="translatedstring",
            name="translated_by_ai",
            field=models.BooleanField(default=False),
        ),
    ]
