# Generated by Django 5.0.7 on 2024-08-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0013_remove_translatablestring_string_fr_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="translatablestring",
            unique_together={("source_project", "string", "context")},
        ),
    ]
