# Generated by Django 5.0.7 on 2024-09-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0014_alter_translatablestring_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceproject",
            name="default_context",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
