# Generated by Django 5.0.7 on 2024-11-27 21:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0015_sourceproject_default_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceproject",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourceproject",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name="sourceproject",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name="sourceproject",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sourceproject",
            name="pageviews",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="sourceproject",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AddField(
            model_name="sourceproject",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),


        migrations.AddField(
            model_name="translatablestring",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translatablestring",
            name="pageviews",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),

        migrations.AddField(
            model_name="translatablestring",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="translatedstring",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translatedstring",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),

        migrations.AddField(
            model_name="translatedstring",
            name="flagged",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="translatedstring",
            name="pageviews",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),

        migrations.AddField(
            model_name="translatedstring",
            name="uuid",
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
