# Generated by Django 5.0.7 on 2024-11-29 07:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translation_api", "0017_sourceproject_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceproject",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="source_project_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="sourceproject",
            name="users",
            field=models.ManyToManyField(blank=True, related_name="source_project_users", to=settings.AUTH_USER_MODEL),
        ),
    ]
