# Generated by Django 5.0.7 on 2025-05-24 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_api', '0019_alter_translatablestring_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatablestring',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
