# Generated by Django 5.0.7 on 2025-05-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_api', '0019_alter_translatablestring_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceproject',
            name='deepl_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
