# Generated by Django 5.0.7 on 2025-05-25 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_api', '0020_sourceproject_deepl_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatablestring',
            name='string',
            field=models.TextField(),
        ),
    ]
