# Generated by Django 5.0.7 on 2025-05-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_api', '0021_alter_translatablestring_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedstring',
            name='translated_string',
            field=models.TextField(),
        ),
    ]
